# Generated by Django 4.2.6 on 2024-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveIntegerField(choices=[(1, 'Великая Отечественная война'), (2, 'Специальная Военная Операция')], verbose_name='Событие')),
                ('firstname', models.CharField(max_length=128, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('midname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('photo', models.FileField(max_length=255, upload_to='heroes', verbose_name='Фото')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('deathdate', models.DateField(verbose_name='Дата смерти')),
                ('grave_place', models.CharField(blank=True, max_length=256, null=True, verbose_name='Место захоронения')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герои',
                'ordering': ['id'],
            },
        ),
    ]
