# Generated by Django 4.2.6 on 2024-05-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveIntegerField(choices=[(1, 'Великая Отечественная война'), (2, 'Специальная Военная Операция')], verbose_name='Событие')),
                ('firstname', models.CharField(max_length=128, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('midname', models.CharField(blank=True, max_length=128, null=True, verbose_name='Отчество')),
                ('photo', models.FileField(max_length=255, upload_to='heroes', verbose_name='Фото')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(max_length=256, verbose_name='Место рождения')),
                ('deathdate', models.DateField(verbose_name='Дата смерти')),
                ('grave_place', models.CharField(max_length=256, verbose_name='Место захоронения')),
                ('rank', models.CharField(blank=True, max_length=128, null=True, verbose_name='Воинское звание')),
                ('feat', models.TextField(blank=True, null=True, verbose_name='Описание подвига')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Одобрено'), (2, 'Отклонено')], editable=False, verbose_name='Статус заявки')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Архив',
                'verbose_name_plural': 'Архив',
                'ordering': ['-id'],
            },
        ),
    ]
