name: Build and push Docker images

on:
  push:
    branches:
      - dev2.0

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Frontend
      run: |
        make install-frontend
        yarn build
        echo "Success frontend"

  test-backend:
    runs-on: ubuntu-lates

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Backend
      run: |
        make install-backend
        echo "Success backend"
