name: Test Install and Build app

on:
  push:
    branches:
      - dev2.0

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Frontend-Install
      run: |
        echo "Success frontend"

    - name: Backend-Install
      run: |
        echo "Success backend"

  build-app:
    needs: test-app
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Dir
        run: |
          pwd
          ls -la
          cd /home/runner/work/glory-trees/glory-trees

      - name: Frontend-Docker
        run: |
          docker image build -t ghcr.io/meowsl/glory-trees:frontend -f deploy/Dockerfile.frontend .
          echo "Success build image for Frontend"

      - name: Backend-Docker
        run: |
          docker image build -t ghcr.io/meowsl/glory-trees:backend -f deploy/Dockerfile.backend .
          echo "Success build image for Backend"
