name: Test Install and Build app

# on:
#   push:
#     branches:
#       - dev2.0

on:
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to host
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            ls -la ~/glory-trees
