name: Test Actions

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run echo command
      run: |
        if [ -n "${{ secrets.SECRET_KEY }}" ]; then
          echo "Successfully retrieved secret key"
        else
          echo "Failed to retrieve secret key"
        fi
