name: Test Install and Build app

on:
  push:
    branches:
      - dev2.0

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Frontend-Install
      run: |
        echo "Success frontend"

    - name: Backend-Install
      run: |
        echo "Success backend"

  build-app:
    needs: test-app
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Check current directory
        run: |
          cd ..
          pwd
          ls -la