name: Test Install and Build app

# on:
#   push:
#     branches:
#       - dev2.0

on:
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy to host
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          key: ${{ secrets.HOST_SSH_KEY }}
          passphrase: meow meow
          script: whoami