name: Test Install and Build app

on:
  push:
    branches:
      - dev2.0

jobs:
  security-backend:
    name: Check Security Backend
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo '${{ secrets.DATABASE_URL }}'
          echo '${{ secrets.SITE_DOMAIN }}'
