name: Build and push Docker images

on:
  push:
    branches:
      - dev2.0

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fronted-Install
      run: |
        make install-frontend
        yarn build
        echo "Success frontend"

    - name: Backend-Install
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.1 python -
        export PATH="${PATH}:/etc/poetry/bin"
        make install-backend
        echo "Success backend"

  build-app:
    needs: test-app
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Frontend-Docker
        run: |
          docker image build -t ghcr.io/meowsl/glory-trees:frontend -f deploy/Dockerfile:frontend .
          echo "Success build image for Frontend"

      - name: Frontend-Docker
        run: |
          docker image build -t ghcr.io/meowsl/glory-trees:backend -f deploy/Dockerfile:backend .
          echo "Success build image for Backend"
