name: Test Install and Build app

on:
  push:
    branches:
      - dev2.0

jobs:

  security-backend:
    name: Check Security Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9.11' ]

    steps:
      - uses: actions/checkout@v2

      - name: Start Bandit
        uses: ./server
        with:
          python_version: ${{ matrix.python-version }}
          project_path: .

      - name: Check Bandit Report
        uses: actions/upload-artifact@v1
        with:
          name: Security reposrt
          path: output/security_report.txt

  install-frontend:
    name: Install Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          make install-frontend
          yarn build
          echo "Success frontend"

  install-backend:
    name: Install Backend
    needs: security-backend
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Poetry
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.1 python -
          export PATH="${PATH}:/etc/poetry/bin"

      - name: Backend-Install
        run: |
          make install-backend
          echo "Success backend"

  build-frontend:
    name: Build Frontend
    needs: install-frontend
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd /home/runner/work/glory-trees/glory-trees
          docker image build -t ghcr.io/meowsl/glory-trees:frontend -f deploy/Dockerfile.frontend .
          echo "Success build image for Frontend"

  build-backend:
    name: Build Backend
    needs: install-backend
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd /home/runner/work/glory-trees/glory-trees
          docker image build -t ghcr.io/meowsl/glory-trees:backend -f deploy/Dockerfile.backend .
          echo "Success build image for Backend"
