name: Build and push Docker images

on:
  push:
    branches:
      - dev2.0

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Frontend
      run: |
        make install-frontend
        yarn build
        echo "Success frontend"

    - name: Test Backend
      run: |
        curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.7.1 python -
        export PATH="${PATH}:/etc/poetry/bin"
        make install-backend
        echo "Success backend"
